name: scope-of-variable

on:
  push:
    branches:
      - main
    
jobs:
  name-of-job-var01:
    runs-on: ubuntu-latest
    
    env:
      name: sindhu
    steps:
      - name: print name
        run: echo ${name} 


