name: scope-of-variable

on:
  push:
    branches:
      - main
    
jobs:
  name-of-job-var01:
    runs-on: ubuntu-latest
    steps:
    
      - name: print name
        run: |
          echo "myName=SindhuV" >> $GITHUB_ENV
          echo "my name in step1 is ${myName}"

      - name: set name
        run: |
          echo "my name in step2 is ${myName}"


  # name-of-job-var02:
  #   runs-on: windows-latest
  #   needs: name-of-job-var01
  #   steps:
  #     - name: printing name from job 1
  #       run: echo "printing name from job 1 the name is $myName"

