name: scope-of-variable

on:
  push:
    branches:
      - main
    
jobs:
  name-of-job-var01:
    runs-on: ubuntu-latest
    
    env:
      name: sindhu
    steps:
    
      - name: print name
        env:
          name: vijay
        run: echo my name is ${name} 


